language: go

go:
  - 1.2
  - 1.3
  - 1.5
  - tip

env:
  matrix:
    - ES_VERSION=1.3.4
    - ES_VERSION=1.4.4
    - ES_VERSION=1.7.3
before_script:
  - mkdir ${HOME}/elasticsearch
  - wget http://download.elastic.co/elasticsearch/elasticsearch/elasticsearch-${ES_VERSION}.tar.gz
  - tar -xzf elasticsearch-${ES_VERSION}.tar.gz -C ${HOME}/elasticsearch
  - ${HOME}/elasticsearch/elasticsearch-${ES_VERSION}/bin/elasticsearch >/dev/null &

script:
  - make test
